### ISSUE TITLE
node-gyp rebuild fails during npm install in client

### ISSUE THREAD

**Issue by virajprabhu** [alasin/Digital-Archive-CBIR#1]
Here's the stack trace.

```
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-            gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-   gyp.js" "rebuild"
gyp ERR! cwd /home/viraj/Documents/code/Digital-Archive-CBIR/Client/node_modules/opencv
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
npm ERR! Failed at the opencv@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the opencv package, 
npm ERR! not with npm itself.
```

Ever faced this?

**Comment by virajprabhu** [comment]
Also, why not add all dev dependencies in package.json? npm install will do a fresh install of all on a user machine.

**Comment by alasin** [comment]
OpenCV node module is not needed actually. Didn't remember to remove it. 

package.json has been updated now, for both Server and Client.
